bigquery_dbt_demo:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('DATASET_NAME') }}"
      threads: 1 # Must be a value of 1 or greater
      keyfile: credentials.json